[build]
  command = "npx tailwindcss -i ./styles.css -o ./dist/styles.css --minify"
  functions = "netlify/functions"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npx tailwindcss -i ./styles.css -o ./dist/styles.css --watch"
  port = 8888
  publish = "."

[context.production.environment]
  DATO_TOKEN = "${DATO_TOKEN}"
